# default configuration

exchange:
  config:
    # turn on debug for default env:
    debug-mode: ${EXCHANGE_DEBUG_MODE:true}

logging:
  level:
    com.itranswarp.exchange: ${LOGGING_EXCHANGE_LEVEL:DEBUG}
